version: "3.7"
services:
  nginx:
    image: nginx
    volumes:
      - $PWD/nginx.conf:/tmp/nginx.conf
    environment: 
      - PLUMBER_SERVER_ADDR=plumber:8000
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - plumber
  plumber:
    build: .
    ports:
      - "8000:8000"
    restart: always

